FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git libz-dev automake libcurl3-dev libbz2-dev liblzma-dev

RUN git clone --recursive https://github.com/samtools/htslib.git
WORKDIR /htslib
RUN autoreconf -i
RUN ./configure
RUN make -j8
RUN make install

COPY . /repo
WORKDIR /repo
RUN make -j8

FROM ubuntu:20.04 as package
COPY --from=builder /repo/build/extractHAIRS /
COPY --from=builder /repo/bam.bam /repo/bam.bam

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y git automake build-essential libz-dev liblzma-dev libbz2-dev
RUN git clone --recursive https://github.com/samtools/htslib.git
WORKDIR /htslib
RUN autoreconf -i
RUN ./configure
RUN make -j8
ENV LD_LIBRARY_PATH=/htslib