FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git libz-dev automake libcurl3-dev libbz2-dev liblzma-dev

RUN git clone --recursive https://github.com/samtools/htslib.git
WORKDIR /htslib
RUN autoreconf -i
RUN ./configure
RUN make -j8
ENV LD_LIBRARY_PATH=/htslib
RUN ldconfig
ENV C_INCLUDE_PATH=/htslib/htslib


ADD . /repo
WORKDIR /repo
RUN make -j8
